/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.itmo;

import org.itmo.manager.CollectionManager;
import org.itmo.manager.CommandManager;
import org.itmo.manager.ConsoleManager;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ConsoleManager consoleManager = new ConsoleManager();
        CollectionManager collectionManager = new CollectionManager();
        CommandManager commandManager = new CommandManager(consoleManager, collectionManager);

        consoleManager.run(commandManager);
    }
}
