/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package itmo_java_lab_5;

import commands.Add;
import manager.CollectionManager;
import manager.CommandManager;
import manager.ConsoleManager;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        CollectionManager collectionManager = new CollectionManager();
        CommandManager commandManager = new CommandManager();
        ConsoleManager consoleManager = new ConsoleManager(commandManager);
        Add addCommand = new Add("add", "Добавление элемента", consoleManager, collectionManager);
        commandManager.register("add", addCommand);
        consoleManager.run();
    }
}
